FROM python:3.10-slim

WORKDIR /app

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    git \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# 安装PyTorch CPU版本
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/  --upgrade pip
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# 安装ModelScope和Diffusers（特定版本）
RUN pip install git+https://github.com/huggingface/diffusers
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/  modelscope 

# RUN pip install git+https://github.com/huggingface/diffusers
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/  transformers accelerate safetensors flask pillow

   # xformers==0.0.23 --no-deps # 可选，CPU上不会使用

# 复制应用文件
COPY app.py .

# 安装模型（可选：在构建时下载，或在运行时挂载）
# RUN python -c "from modelscope import snapshot_download; snapshot_download('Qwen/Qwen-Image')"

# 暴露端口
EXPOSE 5000

# 启动命令
CMD ["python", "app.py"]
# CMD [ "bash -e" ]